### ISSUE TITLE
Use of backticks not explained in curriculum 

### ISSUE THREAD

**Issue by nvstiers** [learn-co-curriculum/js-basics-strings-code-along#2]
When explaining the use of template literals instead of concatenation the curriculum does not explain the need for the use of a backtick instead of single or double quotations in order to get the template literal to work and the .js file to pass the test.

I'm not sure if this is just something the test is looking for or if there is a difference between

``const welcomeMessage = `Welcome to Flatbook, ${currentUser}`;``

and

` const welcomeMessage = 'Welcome to Flatbook, ${currentUser}';`

The confusion i ran into is the tests will pass when concatenating using this code

`const welcomeMessage = 'Welcome to Flatbook, ' + currentUser; + '!';`

which uses single quotations.

some explanation around the differences between the use of quotes when concatenating and the use of backticks when using template literals would be helpful

**Comment by nvstiers** [comment]
After finishing the lesson I noticed there is a mention of the use of backticks as opposed to quotations however it is further down the page and after the first instance of the need for this information. Could be helpful to move it further up on the page.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @nvstiers.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
