### ISSUE TITLE
Never explain how to save from console.

### ISSUE THREAD

**Issue by Asilver-jpg** [learn-co-curriculum/js-basics-strings-code-along#6]
Lab asks to save but never to where or how.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
